from tkinter import *
def go():
    ans = Label(window,text=f"Good bye{e.get()}")
    ans.pack()
window = Tk()
window.title("Introduction")
label1 = Label(window, text="Hello World")
label2 = Label(window, text="This is Rishendra Ruppa")
label1.pack()
label2.pack()
e = Entry(window)
e.pack()
e.get()
button1 = Button(window, text="Add",command=go)
button1.pack()
window.mainloop()