from tkinter import *
#press function
def press(key):
    Exp.insert(END, key)
#solve function
def solve():
    try:
        ans = Label(window, text = f"Answer is {eval(Exp.get())}")
        ans.grid(row = 5, column = 0, columnspan = 2)
    except:
        Exp.delete(0, END)
        Error_label = Label(window, text = "Error")
        Error_label.grid(row = 5, column = 0, columnspan = 2)
def clear():
    Exp.delete(0, END)
window = Tk()
window.title("Calculator")
Exp = Entry(window, width=60)
Exp.get()
Exp.grid(row = 0, column = 0, columnspan = 3)
button_1 = Button(window, text="1", width=10, command=lambda: press(1))
button_2 = Button(window, text="2", width=10,command=lambda: press(2))
button_3 = Button(window, text="3", width=10,command=lambda: press(3))
button_4 = Button(window, text="4", width=10,command=lambda: press(4))
button_5 = Button(window, text="5", width=10,command=lambda: press(5))
button_6 = Button(window, text="6",width=10, command=lambda: press(6))
button_7 = Button(window, text="7",width=10, command=lambda: press(7))
button_8 = Button(window, text="8",width=10, command=lambda: press(8))
button_9 = Button(window, text="9",width=10, command=lambda: press(9))
button_0 = Button(window, text="0",width=10, command=lambda: press(0))

button_add = Button(window, text="+",width=10, command= lambda: press("+"))
button_sub = Button(window, text="-",width=10, command=lambda: press("-"))
button_mul = Button(window, text="*",width=10, command=lambda: press("*"))
button_div = Button(window, text="/",width=10, command=lambda: press("/"))
button_equal = Button(window, text="=",width=10, command=lambda: solve())
button_clear = Button(window, text="C",width=10, command=lambda: clear())
button_1.grid(row = 1, column = 0)
button_2.grid(row = 1, column = 1)
button_3.grid(row = 1, column = 2)
button_4.grid(row = 2, column = 0)
button_5.grid(row = 2, column = 1)
button_6.grid(row = 2, column = 2)
button_7.grid(row = 3, column = 0)
button_8.grid(row = 3, column = 1)
button_9.grid(row = 3, column = 2)
button_0.grid(row = 4, column = 0)
button_add.grid(row = 1, column = 3)
button_sub.grid(row = 2, column = 3)
button_mul.grid(row = 3, column = 3)
button_div.grid(row = 4, column = 1)
button_equal.grid(row = 4, column = 2)
button_clear.grid(row = 4, column = 3)
window.mainloop()
