import smtplib as st
import datetime as dt
import random
from DAY32.Sending_mail import connection

motivational_quotes = [
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "It always seems impossible until it’s done. – Nelson Mandela",
    "Act as if what you do makes a difference. It does. – William James",
    "Start where you are. Use what you have. Do what you can. – Arthur Ashe",
    "With the new day comes new strength and new thoughts. – Eleanor Roosevelt",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Wish it. Do it.",
    "Stay positive. Work hard. Make it happen.",
    "Success is what comes after you stop making excuses.",
    "Great things are done by a series of small things brought together. – Vincent Van Gogh",
    "The way to get started is to quit talking and begin doing. – Walt Disney",
    "Don’t let yesterday take up too much of today. – Will Rogers",
    "You learn more from failure than from success. – Unknown",
    "Failure will never overtake me if my determination to succeed is strong enough. – Og Mandino",
    "We may encounter many defeats but we must not be defeated. – Maya Angelou",
    "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
    "Everything you’ve ever wanted is on the other side of fear. – George Addair",
    "Opportunities don’t happen. You create them. – Chris Grosser",
    "Do what you can with all you have, wherever you are. – Theodore Roosevelt",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar",
    "Be not afraid of going slowly, be afraid only of standing still. – Chinese Proverb",
    "In the middle of every difficulty lies opportunity. – Albert Einstein",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett",
    "If you want to fly, give up everything that weighs you down.",
    "Doubt kills more dreams than failure ever will. – Suzy Kassem",
    "Discipline is doing what needs to be done, even if you don’t want to do it.",
    "You are capable of amazing things.",
    "Work hard in silence. Let your success be the noise.",
    "A little progress each day adds up to big results.",
    "Stay focused, go after your dreams, and keep moving toward your goals.",
    "Don't limit your challenges, challenge your limits.",
    "Sometimes later becomes never. Do it now.",
    "Strive for progress, not perfection.",
    "Your only limit is your mind.",
    "Push harder than yesterday if you want a different tomorrow.",
    "Failure is not the opposite of success, it’s part of success.",
    "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
    "The secret of getting ahead is getting started. – Mark Twain",
    "You don’t need to see the whole staircase, just take the first step. – Martin Luther King Jr.",
    "Work gives you meaning and purpose, and life is empty without it. – Stephen Hawking",
    "There is no substitute for hard work. – Thomas Edison",
    "If something is important enough, even if the odds are against you, you should still do it. – Elon Musk",
    "Go the extra mile. It’s never crowded.",
    "Don’t count the days, make the days count. – Muhammad Ali",
    "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
    "The future depends on what you do today. – Mahatma Gandhi",
    "Energy and persistence conquer all things. – Benjamin Franklin",
    "When you feel like quitting, think about why you started.",
    "Be stronger than your excuses.",
    "Either you run the day or the day runs you. – Jim Rohn",
    "You miss 100% of the shots you don’t take. – Wayne Gretzky",
    "You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction. – George Lorimer",
    "Hustle in silence and let your success make the noise.",
    "Winners are not afraid of losing. But losers are. – Robert Kiyosaki",
    "Make each day your masterpiece. – John Wooden",
    "The pain you feel today will be the strength you feel tomorrow.",
    "Don’t limit yourself. You can go as far as your mind lets you.",
    "You can’t cross the sea merely by standing and staring at the water. – Rabindranath Tagore",
    "Action is the foundational key to all success. – Pablo Picasso",
    "Take risks: if you win, you will be happy; if you lose, you will be wise.",
    "A goal without a plan is just a wish. – Antoine de Saint-Exupéry",
    "Success is not in what you have, but who you are. – Bo Bennett",
    "Worry less, do more.",
    "One day or day one. You decide.",
    "If you get tired, learn to rest, not quit. – Banksy",
    "Do not wait for the perfect time and place to enter, for you are already onstage. – Unknown",
    "The comeback is always stronger than the setback.",
    "Turn your wounds into wisdom. – Oprah Winfrey",
    "Stay hungry. Stay foolish. – Steve Jobs",
    "If you believe it will work out, you’ll see opportunities. If you believe it won’t, you’ll see obstacles. – Wayne Dyer",
    "Don’t be afraid to give up the good to go for the great. – John D. Rockefeller",
    "Start today, not tomorrow. If anything, you should have started yesterday.",
    "Make your life a masterpiece; imagine no limitations on what you can be, have or do. – Brian Tracy",
    "Be so good they can’t ignore you. – Steve Martin",
    "The best way to predict the future is to create it. – Peter Drucker",
    "Champions keep playing until they get it right. – Billie Jean King",
    "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice. – Pelé",
    "All our dreams can come true if we have the courage to pursue them. – Walt Disney",
    "Do the best you can until you know better. Then when you know better, do better. – Maya Angelou",
    "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
    "If you’re going through hell, keep going. – Winston Churchill",
    "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway. – Earl Nightingale"
]

my_mail = "<EMAIL>"
password = "<PASSWORD>"
time = dt.datetime.now()
weekday = time.weekday()
if weekday == 1:
    connection = st.SMTP("smtp.gmail.com",587)
    connection.starttls()
    connection.login(user=my_mail,password=password)
    connection.sendmail(
        from_addr=my_mail,
        to_addrs=my_mail,
        message=f"Subject: hello\n\n{time} \n Quote of the day : \n {random.choice(motivational_quotes)}"
)